### ISSUE TITLE
Create an Image object

### ISSUE THREAD

**Issue by ChameleonIVCR** [ChameleonIVCR/AlphaExeSharp#2]
Create an Image object to store image data and include methods into it to convert into other formats.
Image class should store:
- [x]  Image filename
- [x]  Image path
- [x]  Image format
- [x]  Setter
- [x]  Getter
- [x]  Conversion methods

and any other image data needed for conversion purposes.

**Comment by iamawesome99** [comment]
did i do this or am i dumb and did something different

**Comment by ChameleonIVCR** [comment]
50% 50%
